server {
    listen 127.0.0.1:8686;
    server_name git.tindango;
    server_tokens off;

    root /usr/share/webapps/cgit;

    # Block pushes
    if ($arg_service = git-receive-pack) {
        return 403;
    }

    location ~ ^/.+\.git/git-receive-pack$ {
        return 403;
    }

    # Git clone/fetch
    location ~ ^/.+\.git/(info/refs|git-upload-pack)$ {
        include fastcgi_params;

        fastcgi_pass unix:/run/fcgiwrap.sock;
        fastcgi_param SCRIPT_FILENAME /usr/lib/git-core/git-http-backend;
        fastcgi_param PATH_INFO $uri;
        fastcgi_param GIT_HTTP_EXPORT_ALL 1;
        fastcgi_param GIT_PROJECT_ROOT /var/ci/repos;
        fastcgi_param HOME /var/ci/repos;
        fastcgi_param GIT_PROTOCOL $http_git_protocol;
    }

    # Serve cgit.css, cgit.js, cgit.png, favicon.ico, robots.txt, etc.
    try_files $uri @cgit;

    # cgit CGI
    location @cgit {
        include fastcgi_params;

        fastcgi_pass unix:/run/fcgiwrap.sock;
        fastcgi_param SCRIPT_FILENAME /usr/lib/cgit/cgit.cgi;
        fastcgi_param PATH_INFO $uri;
        fastcgi_param QUERY_STRING $args;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param CGIT_CONFIG /etc/cgitrc;
    }
}
