datadir = /home/postal/smtpmailvar/data/maildir/new
logdir = /home/postal/smtpmailvar/logs
certificate = /etc/ssl/private/mail.tindango.com/certificate.crt
privatekey = /etc/ssl/private/mail.tindango.com/private.key

# host = 0.0.0.0
budget = eco
proxy_support = true
# port = 2525
# timeout = 120

# default: 512KB
# email_limit_size = 524288
