apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: router-peer
spec:
  peerIP: 10.0.0.1
  asNumber: 64513
  nodeSelector: "!has(calico/no-bgp)" # Apply to all nodes unless tagged otherwise
