apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nodejs-hello-world-service-1 # by convention, use the name of the Service
                     # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: nodejs-hello-world-service
addressType: IPv4
ports:
  - name: http # should match with the name of the service port defined above
    appProtocol: http
    protocol: TCP
    port: 3000
endpoints:
  - addresses:
      - "10.0.0.100"
