[Unit]
Wants=network-online.target
Wants=mariadb.service
Wants=NetworkManager-wait-online.service
After=network-online.target
After=time-sync.target
After=mariadb.service
After=NetworkManager-wait-online.service
Requires=NetworkManager-wait-online.service

[Service]
MemoryMax=64M
Restart=on-failure
