###############################
# git server nginx configuration
###############################

#user http;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


# Load all installed modules
include modules.d/*.conf;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;


    types_hash_max_size 4096;
    types_hash_bucket_size 128;

    sendfile        on;
    keepalive_timeout 65;

    include conf.d/*.conf;
}
